spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email
            client-name: naver
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
        provider:
          naver:
            user-name-attribute: response
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-info-uri: https://openapi.naver.com/v1/nid/me
            token-uri: https://nid.naver.com/oauth2.0/token
  application:
    name: vacit
#  profiles:
#    active: "local"
#    group:
#      "local": "localDB, devPort, secret, web-mvc"
#      "dev": "devDB, devPort, secret, web-mvc"
#      "prod": "prodDB, prodPort, secret, web-mvc"