spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email
            client-name: naver
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
        provider:
          naver:
            user-name-attribute: response
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-info-uri: https://openapi.naver.com/v1/nid/me
            token-uri: https://nid.naver.com/oauth2.0/token
  application:
    name: vacit

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./data/demo
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create # 테이블 생성 전략 - create: 항상 생성
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      encoding: UTF-8
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true # 다른 사용자 접속 허용
#  profiles:
#    active: "local"
#    group:
#      "local": "localDB, devPort, secret, web-mvc"
#      "dev": "devDB, devPort, secret, web-mvc"
#      "prod": "prodDB, prodPort, secret, web-mvc"