spring:
  profiles:
    active: "local"
    group:
      "local": "test"
      "prod": "test, prodDB"
---
spring:
  config:
    activate:
      on-profile: test
  security:
    oauth2:
      client:
        registration:
          naver:
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email
            client-name: naver
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
        provider:
          naver:
            user-name-attribute: response
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-info-uri: https://openapi.naver.com/v1/nid/me
            token-uri: https://nid.naver.com/oauth2.0/token
  application:
    name: vacit

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./data/demo
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update # 테이블 생성 전략 - update: 테이블이 없을 때만 생성
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true # 다른 사용자 접속 허용

---

spring:
  config:
    activate:
      on-profile: prodDB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.cb4se2ckk9tm.ap-northeast-2.rds.amazonaws.com:3306/vacit
    username: admin
    password: qwer1234
  jpa:
    hibernate:
      ddl-auto: update # 테이블 생성 전략 - update: 테이블이 없을 때만 생성


